main: com.github.AndrewAlbizati.Plugin
name: DiscordIntegrationPlugin
version: 1.0.1
description: This plugin is used to connect Discord servers with Minecraft servers, and creates a bidirectional chat system with the two.
author: Andrew Albizati
api-version: 1.19